info:
  contact: {}
paths:
  /product:
    get:
      consumes:
      - application/json
      description: get products
      produces:
      - application/json
      responses: {}
      summary: List products
      tags:
      - Product
swagger: "2.0"
